# Generated by Django 5.2.1 on 2025-05-26 03:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanningRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subjects",
                    models.CharField(
                        help_text="Materias separadas por comas", max_length=255
                    ),
                ),
                (
                    "course",
                    models.CharField(
                        help_text="Nivel o grado de impartición", max_length=100
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "planning_type",
                    models.CharField(
                        choices=[
                            ("anual", "Anual"),
                            ("microcurricular", "Microcurricular"),
                            ("semanal", "Semanal"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "number_units",
                    models.PositiveIntegerField(
                        help_text="Número de unidades a impartir"
                    ),
                ),
                (
                    "generated_pdf",
                    models.FileField(
                        blank=True, null=True, upload_to="planifications/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendiente"),
                            ("processing", "Procesando"),
                            ("completed", "Completado"),
                            ("failed", "Fallido"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
